### ISSUE TITLE
How to use the FunCorp module?

### ISSUE THREAD

**Issue by RiquelmeMagal** [JW26T-Prj/FunCorpModules#2]
Hello dear friend. I'm a conventional player, and I would like to use the Funcorp mode for players on the Brazilian server, is it possible? Or just staff players?
1. If a conventional player can use the module freely, how does it work?
2. I saw a player with a module called "long jump" on Funcorp and I wanted to be able to play with all Brazilians.
See you later!

**Comment by JW26T-Prj** [comment]
You can freely use the module. Just copy the entire code (i recommend using the Raw button to this), paste into your /lua and load into your tribehouse.
But any FunCorp-related functions will not work, because they are designed for use only with FunCorp members.
